/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#f7f9fb",
        "tertiary-container": "#773900",
        background: "#f7f9fb",
        outline: "#727780",
        "secondary-container": "#a0f399",
        "primary-fixed-dim": "#a0c9ff",
        "surface-tint": "#2d6197",
        "on-background": "#191c1e",
        "on-surface": "#191c1e",
        "surface-container-highest": "#e0e3e5",
        "surface-container-low": "#f2f4f6",
        "on-error-container": "#93000a",
        "on-tertiary": "#ffffff",
        primary: "#00355f",
        "surface-variant": "#e0e3e5",
        secondary: "#1b6d24",
        "on-primary": "#ffffff",
        "secondary-fixed-dim": "#88d982",
        "inverse-surface": "#2d3133",
        "surface-bright": "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "primary-container": "#0f4c81",
        "on-secondary-fixed": "#002204",
        "tertiary-fixed": "#ffdcc6",
        "surface-container": "#eceef0",
        "on-tertiary-container": "#ffa564",
        "on-surface-variant": "#42474f",
        "outline-variant": "#c2c7d1",
        tertiary: "#552700",
        "on-error": "#ffffff",
        "primary-fixed": "#d2e4ff",
        "on-primary-fixed": "#001c37",
        "tertiary-fixed-dim": "#ffb786",
        "on-tertiary-fixed": "#311300",
        "surface-container-high": "#e6e8ea",
        error: "#ba1a1a",
        "inverse-primary": "#a0c9ff",
        "on-primary-fixed-variant": "#07497d",
        "surface-dim": "#d8dadc",
        "inverse-on-surface": "#eff1f3",
        "on-tertiary-fixed-variant": "#723600",
        "on-secondary-container": "#217128",
        "secondary-fixed": "#a3f69c",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#005312",
        "on-primary-container": "#8ebdf9",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-desktop": "40px",
        gutter: "24px",
        base: "8px",
        "margin-mobile": "16px",
        "container-max": "1200px",
      },
      fontFamily: {
        "headline-md": ["Manrope"],
        "body-md": ["Inter"],
        "headline-xl": ["Manrope"],
        "headline-lg-mobile": ["Manrope"],
        "label-md": ["Inter"],
        "headline-lg": ["Manrope"],
        "body-lg": ["Inter"],
        "label-bold": ["Inter"],
        "body-sm": ["Inter"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", fontWeight: "700" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-bold": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
}
